-- Aligns the local PostgreSQL schema with what api/index.js reads and writes.
-- Idempotent: safe to re-run. Written for the local development database.
BEGIN;

-- Missing tables
CREATE TABLE IF NOT EXISTS conference_roles (
  id serial PRIMARY KEY,
  conference_id varchar NOT NULL,
  email_id varchar NOT NULL,
  role varchar NOT NULL
);
CREATE TABLE IF NOT EXISTS desk_review (
  id serial PRIMARY KEY,
  paper_id varchar NOT NULL,
  decision varchar,
  user_email varchar,
  remarks text,
  created_at timestamp DEFAULT now()
);
CREATE TABLE IF NOT EXISTS meta_reviewer_decision (
  id serial PRIMARY KEY,
  submission_id varchar NOT NULL,
  status varchar,
  remarks text
);

-- Missing columns
ALTER TABLE users ADD COLUMN IF NOT EXISTS role varchar;
ALTER TABLE chairs ADD COLUMN IF NOT EXISTS status varchar;
ALTER TABLE conference_tracks ADD COLUMN IF NOT EXISTS status varchar;
ALTER TABLE conference_tracks ADD COLUMN IF NOT EXISTS session_code varchar;
ALTER TABLE conference_tracks ADD COLUMN IF NOT EXISTS meta_reviewer varchar;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS remarks text;
ALTER TABLE revised_submissions ADD COLUMN IF NOT EXISTS reviewer varchar;
ALTER TABLE revised_submissions ADD COLUMN IF NOT EXISTS remarks text;
ALTER TABLE conferences ADD COLUMN IF NOT EXISTS communication text[];

-- Type mismatches (code treats these as arrays / booleans / uuids)
ALTER TABLE conferences ALTER COLUMN co_chairs TYPE text[] USING CASE WHEN co_chairs IS NULL THEN NULL ELSE string_to_array(co_chairs, ',') END;
ALTER TABLE poster_session ALTER COLUMN coodinators TYPE text[] USING CASE WHEN coodinators IS NULL THEN NULL ELSE string_to_array(coodinators, ',') END;
ALTER TABLE submissions ALTER COLUMN track_id TYPE uuid USING track_id::uuid;
ALTER TABLE submissions ALTER COLUMN is_ai TYPE boolean USING is_ai::boolean;

-- Generated keys the code relies on being filled by the database
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='peer_review' AND column_name='id' AND is_identity='YES') THEN
    ALTER TABLE peer_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='chairs' AND column_name='user_id' AND is_identity='YES') THEN
    ALTER TABLE chairs ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

COMMIT;
