--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
-- SET transaction_timeout = 0;  -- Not supported in PostgreSQL 15
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: chair; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chair (
    id bigint NOT NULL,
    name text,
    email_id character varying,
    profile_picture character varying,
    uid character varying
);


ALTER TABLE public.chair OWNER TO postgres;

--
-- Name: chair_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chair ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chair_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: co_author_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.co_author_requests (
    conference_id character varying,
    submission_id character varying,
    primary_author character varying,
    co_author character varying,
    status text,
    request_id uuid DEFAULT gen_random_uuid() NOT NULL
);


ALTER TABLE public.co_author_requests OWNER TO postgres;

--
-- Name: conference_tracks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.conference_tracks (
    track_name text,
    track_reviewers text[],
    presentation_date date,
    presentation_start_time time without time zone,
    presentation_end_time time without time zone,
    panelists character varying[],
    status text,
    track_id uuid DEFAULT gen_random_uuid() NOT NULL,
    conference_id character varying
);


ALTER TABLE public.conference_tracks OWNER TO postgres;

--
-- Name: conferences; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.conferences (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    title text,
    description text,
    conference_start_date date,
    conference_end_date date,
    full_paper_submission date,
    acceptance_notification date,
    camera_ready_paper_submission date,
    conference_id uuid DEFAULT gen_random_uuid() NOT NULL
);


ALTER TABLE public.conferences OWNER TO postgres;

--
-- Name: TABLE conferences; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.conferences IS 'database of conferences';


--
-- Name: final_camera_ready_submissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.final_camera_ready_submissions (
    conference_id character varying,
    title text,
    abstract text,
    track_id text,
    co_authors text,
    file_url character varying,
    status text,
    panelist_score real,
    primary_author text,
    submission_id uuid NOT NULL
);


ALTER TABLE public.final_camera_ready_submissions OWNER TO postgres;

--
-- Name: invited_talk_submissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invited_talk_submissions (
    invitee_email character varying,
    conference_id character varying,
    title text,
    abstract text,
    file_url character varying,
    track_id text,
    paper_id uuid DEFAULT gen_random_uuid() NOT NULL
);


ALTER TABLE public.invited_talk_submissions OWNER TO postgres;

--
-- Name: invitees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invitees (
    invite_id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text,
    email character varying,
    conference_id character varying,
    password_hash character varying,
    password_reset_token text,
    password_reset_expires timestamp with time zone
);


ALTER TABLE public.invitees OWNER TO postgres;

--
-- Name: peer_review; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.peer_review (
    id bigint NOT NULL,
    conference_id character varying,
    submission_id character varying,
    originality_score real,
    relevance_score real,
    technical_quality_score real,
    clarity_score real,
    impact_score real,
    mean_score real,
    acceptance_status text,
    remarks text,
    reviewer text,
    review_status text
);


ALTER TABLE public.peer_review OWNER TO postgres;

--
-- Name: peer_review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.peer_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.peer_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: poster_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.poster_session (
    poster_session_id uuid DEFAULT gen_random_uuid() NOT NULL,
    conference_id character varying,
    date date,
    start_time time without time zone,
    end_time time without time zone
);


ALTER TABLE public.poster_session OWNER TO postgres;

--
-- Name: revised_submissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.revised_submissions (
    submission_id character varying NOT NULL,
    file_url character varying,
    originality_score real,
    relevance_score real,
    technical_quality_score real,
    clarity_score real,
    impact_score real,
    mean_score real,
    acceptance_status text,
    review_status text
);


ALTER TABLE public.revised_submissions OWNER TO postgres;

--
-- Name: submissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.submissions (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    conference_id character varying,
    primary_author character varying,
    title text,
    abstract text,
    track_id text,
    file_url character varying,
    paper_code character varying,
    co_authors text[],
    submission_status text DEFAULT 'Submitted for Review'::text,
    submission_id uuid DEFAULT gen_random_uuid() NOT NULL
);


ALTER TABLE public.submissions OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    uid character varying,
    name text,
    email character varying,
    profile_picture character varying,
    password_hash character varying,
    password_reset_token text,
    password_reset_expires timestamp with time zone
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: TABLE users; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.users IS 'database of confease users';


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chair chair_email_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chair
    ADD CONSTRAINT chair_email_id_key UNIQUE (email_id);


--
-- Name: chair chair_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chair
    ADD CONSTRAINT chair_pkey PRIMARY KEY (id);


--
-- Name: co_author_requests co_author_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.co_author_requests
    ADD CONSTRAINT co_author_requests_pkey PRIMARY KEY (request_id);


--
-- Name: conference_tracks conference_tracks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conference_tracks
    ADD CONSTRAINT conference_tracks_pkey PRIMARY KEY (track_id);


--
-- Name: conferences conferences_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conferences
    ADD CONSTRAINT conferences_pkey PRIMARY KEY (conference_id);


--
-- Name: final_camera_ready_submissions final_camera_ready_submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.final_camera_ready_submissions
    ADD CONSTRAINT final_camera_ready_submissions_pkey PRIMARY KEY (submission_id);


--
-- Name: invited_talk_submissions invited_talk_submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invited_talk_submissions
    ADD CONSTRAINT invited_talk_submissions_pkey PRIMARY KEY (paper_id);


--
-- Name: invitees invitees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invitees
    ADD CONSTRAINT invitees_pkey PRIMARY KEY (invite_id);


--
-- Name: peer_review peer_review_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.peer_review
    ADD CONSTRAINT peer_review_pkey PRIMARY KEY (id);


--
-- Name: poster_session poster_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.poster_session
    ADD CONSTRAINT poster_session_pkey PRIMARY KEY (poster_session_id);


--
-- Name: revised_submissions revised_submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.revised_submissions
    ADD CONSTRAINT revised_submissions_pkey PRIMARY KEY (submission_id);


--
-- Name: submissions submissions_paper_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT submissions_paper_code_key UNIQUE (paper_code);


--
-- Name: submissions submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT submissions_pkey PRIMARY KEY (submission_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: conferences Allow all users to read; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow all users to read" ON public.conferences FOR SELECT USING (true);


--
-- Name: chair chair_manage_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY chair_manage_chairs ON public.chair USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text)) WITH CHECK ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: chair chair_read_self; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY chair_read_self ON public.chair FOR SELECT USING ((((email_id)::text = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text)) OR (((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text)));


--
-- Name: co_author_requests co_author_requests_insert_authors; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY co_author_requests_insert_authors ON public.co_author_requests FOR INSERT WITH CHECK ((((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text) IN ( SELECT DISTINCT submissions.primary_author
   FROM public.submissions
  WHERE ((submissions.submission_id)::text = (co_author_requests.submission_id)::text))));


--
-- Name: co_author_requests co_author_requests_manage_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY co_author_requests_manage_chairs ON public.co_author_requests USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text)) WITH CHECK ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: co_author_requests co_author_requests_read_authors; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY co_author_requests_read_authors ON public.co_author_requests FOR SELECT USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text) IN ( SELECT DISTINCT submissions.primary_author
   FROM public.submissions
  WHERE ((submissions.submission_id)::text = (co_author_requests.submission_id)::text))));


--
-- Name: co_author_requests co_author_requests_read_target; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY co_author_requests_read_target ON public.co_author_requests FOR SELECT USING ((((co_author)::text = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text)) OR (((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text) IN ( SELECT DISTINCT submissions.primary_author
   FROM public.submissions
  WHERE ((submissions.submission_id)::text = (co_author_requests.submission_id)::text)))));


--
-- Name: co_author_requests co_author_requests_update_target; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY co_author_requests_update_target ON public.co_author_requests FOR UPDATE USING (((co_author)::text = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text))) WITH CHECK (((co_author)::text = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text)));


--
-- Name: conferences conferences_delete_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY conferences_delete_chairs ON public.conferences FOR DELETE USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: conferences conferences_manage_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY conferences_manage_chairs ON public.conferences FOR INSERT WITH CHECK ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: conferences conferences_read_all; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY conferences_read_all ON public.conferences FOR SELECT USING (true);


--
-- Name: conferences conferences_update_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY conferences_update_chairs ON public.conferences FOR UPDATE USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text)) WITH CHECK ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: final_camera_ready_submissions final_camera_ready_manage_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY final_camera_ready_manage_chairs ON public.final_camera_ready_submissions USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text)) WITH CHECK ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: final_camera_ready_submissions final_camera_ready_read_authors; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY final_camera_ready_read_authors ON public.final_camera_ready_submissions FOR SELECT USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text) IN ( SELECT DISTINCT submissions.primary_author
   FROM public.submissions
  WHERE (submissions.submission_id = final_camera_ready_submissions.submission_id)
UNION
 SELECT DISTINCT unnest(submissions.co_authors) AS unnest
   FROM public.submissions
  WHERE (submissions.submission_id = final_camera_ready_submissions.submission_id))));


--
-- Name: final_camera_ready_submissions final_camera_ready_read_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY final_camera_ready_read_chairs ON public.final_camera_ready_submissions FOR SELECT USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: invited_talk_submissions invited_talk_submissions_insert_invitees; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY invited_talk_submissions_insert_invitees ON public.invited_talk_submissions FOR INSERT WITH CHECK (((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'invitee'::text) AND ((invitee_email)::text = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text))));


--
-- Name: invited_talk_submissions invited_talk_submissions_manage_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY invited_talk_submissions_manage_chairs ON public.invited_talk_submissions USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text)) WITH CHECK ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: invited_talk_submissions invited_talk_submissions_read_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY invited_talk_submissions_read_chairs ON public.invited_talk_submissions FOR SELECT USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: invited_talk_submissions invited_talk_submissions_read_invitees; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY invited_talk_submissions_read_invitees ON public.invited_talk_submissions FOR SELECT USING (((invitee_email)::text = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text)));


--
-- Name: invited_talk_submissions invited_talk_submissions_update_invitees; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY invited_talk_submissions_update_invitees ON public.invited_talk_submissions FOR UPDATE USING (((invitee_email)::text = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text))) WITH CHECK (((invitee_email)::text = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text)));


--
-- Name: invitees invitees_manage_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY invitees_manage_chairs ON public.invitees USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text)) WITH CHECK ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: invitees invitees_read_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY invitees_read_chairs ON public.invitees FOR SELECT USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: invitees invitees_read_self; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY invitees_read_self ON public.invitees FOR SELECT USING (((email)::text = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text)));


--
-- Name: peer_review peer_review_insert_reviewers; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY peer_review_insert_reviewers ON public.peer_review FOR INSERT WITH CHECK (((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'reviewer'::text) AND (reviewer = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text))));


--
-- Name: peer_review peer_review_manage_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY peer_review_manage_chairs ON public.peer_review USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text)) WITH CHECK ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: peer_review peer_review_read_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY peer_review_read_chairs ON public.peer_review FOR SELECT USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: peer_review peer_review_read_reviewers; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY peer_review_read_reviewers ON public.peer_review FOR SELECT USING ((reviewer = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text)));


--
-- Name: peer_review peer_review_update_reviewers; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY peer_review_update_reviewers ON public.peer_review FOR UPDATE USING ((reviewer = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text))) WITH CHECK ((reviewer = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text)));


--
-- Name: poster_session poster_session_manage_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY poster_session_manage_chairs ON public.poster_session USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text)) WITH CHECK ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: poster_session poster_session_read_all; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY poster_session_read_all ON public.poster_session FOR SELECT USING (true);


--
-- Name: revised_submissions revised_submissions_manage_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY revised_submissions_manage_chairs ON public.revised_submissions USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text)) WITH CHECK ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: revised_submissions revised_submissions_read_authors; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY revised_submissions_read_authors ON public.revised_submissions FOR SELECT USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text) IN ( SELECT DISTINCT submissions.primary_author
   FROM public.submissions
  WHERE ((submissions.submission_id)::text = (revised_submissions.submission_id)::text)
UNION
 SELECT DISTINCT unnest(submissions.co_authors) AS unnest
   FROM public.submissions
  WHERE ((submissions.submission_id)::text = (revised_submissions.submission_id)::text))));


--
-- Name: revised_submissions revised_submissions_read_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY revised_submissions_read_chairs ON public.revised_submissions FOR SELECT USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: revised_submissions revised_submissions_read_reviewers; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY revised_submissions_read_reviewers ON public.revised_submissions FOR SELECT USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'reviewer'::text));


--
-- Name: revised_submissions revised_submissions_update_authors; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY revised_submissions_update_authors ON public.revised_submissions FOR UPDATE USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text) IN ( SELECT DISTINCT submissions.primary_author
   FROM public.submissions
  WHERE ((submissions.submission_id)::text = (revised_submissions.submission_id)::text)
UNION
 SELECT DISTINCT unnest(submissions.co_authors) AS unnest
   FROM public.submissions
  WHERE ((submissions.submission_id)::text = (revised_submissions.submission_id)::text)))) WITH CHECK ((((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text) IN ( SELECT DISTINCT submissions.primary_author
   FROM public.submissions
  WHERE ((submissions.submission_id)::text = (revised_submissions.submission_id)::text)
UNION
 SELECT DISTINCT unnest(submissions.co_authors) AS unnest
   FROM public.submissions
  WHERE ((submissions.submission_id)::text = (revised_submissions.submission_id)::text))));


--
-- Name: submissions submissions_insert_authors; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY submissions_insert_authors ON public.submissions FOR INSERT WITH CHECK (((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'author'::text) AND ((primary_author)::text = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text))));


--
-- Name: submissions submissions_manage_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY submissions_manage_chairs ON public.submissions USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text)) WITH CHECK ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: submissions submissions_read_authors; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY submissions_read_authors ON public.submissions FOR SELECT USING ((((primary_author)::text = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text)) OR ((co_authors IS NOT NULL) AND (co_authors @> ARRAY[((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text)]))));


--
-- Name: submissions submissions_read_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY submissions_read_chairs ON public.submissions FOR SELECT USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: submissions submissions_read_reviewers; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY submissions_read_reviewers ON public.submissions FOR SELECT USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'reviewer'::text));


--
-- Name: submissions submissions_update_authors; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY submissions_update_authors ON public.submissions FOR UPDATE USING ((((primary_author)::text = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text)) OR ((co_authors IS NOT NULL) AND (co_authors @> ARRAY[((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text)])))) WITH CHECK ((((primary_author)::text = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text)) OR ((co_authors IS NOT NULL) AND (co_authors @> ARRAY[((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text)]))));


--
-- Name: conference_tracks tracks_delete_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY tracks_delete_chairs ON public.conference_tracks FOR DELETE USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: conference_tracks tracks_manage_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY tracks_manage_chairs ON public.conference_tracks FOR INSERT WITH CHECK ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: conference_tracks tracks_read_all; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY tracks_read_all ON public.conference_tracks FOR SELECT USING (true);


--
-- Name: conference_tracks tracks_update_chairs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY tracks_update_chairs ON public.conference_tracks FOR UPDATE USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text)) WITH CHECK ((((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'chair'::text));


--
-- Name: users users_read_self; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY users_read_self ON public.users FOR SELECT USING (((email)::text = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text)));


--
-- Name: users users_update_self; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY users_update_self ON public.users FOR UPDATE USING (((email)::text = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text))) WITH CHECK (((email)::text = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text)));


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- Name: TABLE chair; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.chair TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.chair TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.chair TO service_role;


--
-- Name: SEQUENCE chair_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.chair_id_seq TO anon;
GRANT ALL ON SEQUENCE public.chair_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.chair_id_seq TO service_role;


--
-- Name: TABLE co_author_requests; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.co_author_requests TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.co_author_requests TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.co_author_requests TO service_role;


--
-- Name: TABLE conference_tracks; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.conference_tracks TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.conference_tracks TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.conference_tracks TO service_role;


--
-- Name: TABLE conferences; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.conferences TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.conferences TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.conferences TO service_role;


--
-- Name: TABLE final_camera_ready_submissions; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.final_camera_ready_submissions TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.final_camera_ready_submissions TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.final_camera_ready_submissions TO service_role;


--
-- Name: TABLE invited_talk_submissions; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.invited_talk_submissions TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.invited_talk_submissions TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.invited_talk_submissions TO service_role;


--
-- Name: TABLE invitees; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.invitees TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.invitees TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.invitees TO service_role;


--
-- Name: TABLE peer_review; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.peer_review TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.peer_review TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.peer_review TO service_role;


--
-- Name: SEQUENCE peer_review_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.peer_review_id_seq TO anon;
GRANT ALL ON SEQUENCE public.peer_review_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.peer_review_id_seq TO service_role;


--
-- Name: TABLE poster_session; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.poster_session TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.poster_session TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.poster_session TO service_role;


--
-- Name: TABLE revised_submissions; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.revised_submissions TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.revised_submissions TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.revised_submissions TO service_role;


--
-- Name: TABLE submissions; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.submissions TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.submissions TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.submissions TO service_role;


--
-- Name: TABLE users; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.users TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.users TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.users TO service_role;


--
-- Name: SEQUENCE users_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.users_id_seq TO anon;
GRANT ALL ON SEQUENCE public.users_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.users_id_seq TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO service_role;


--
-- PostgreSQL database dump complete
--

